### ISSUE TITLE
Fatal error: Uncaught exception 'CasperException' with message 'Operation timed out after 10000 milliseconds 

### ISSUE THREAD

**Issue by waveur35** [mgp25/SC-API#238] opened 2015-10-18 19:50 UTC
Hello,

I've got a problem with the API. An issus was already opened for this but there is no solution in it. So there is my actual problem : 

`Fatal error: Uncaught exception 'CasperException' with message 'Operation timed out after 10000 milliseconds with 0 bytes received' in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php:163 Stack trace: #0 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php(95): CasperAgent->request('/snapchat/attes...', NULL, Array, true) #1 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAPI.php(92): CasperAgent->post('/snapchat/attes...', NULL, Array) #2 C:\inetpub\wwwroot\src\snapchat.php(151): CasperAPI->getSnapchatAttestation('ZwLa9SeU6Q5TRUS...') #3 C:\inetpub\wwwroot\src\snapchat.php(362): Snapchat->getAttestation('sddsfs', 'sddsfs', 1445197301348) #4 C:\inetpub\wwwroot\script\all\lisahellx.php(203): Snapchat->login('sddsfs') #5 {main} thrown in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php on line 163`

Every time I try to send story, i've got this error..

Is this an API problem ?

**Comment by mgp25** [comment] 2015-10-18 20:41
@waveur35 please quote the log, please!

**Comment by waveur35** [comment] 2015-10-18 20:55
Sorry, thanks a lot for the fix but it don't work actually.. Now i've this error : 

[quote]
Fatal error: Uncaught exception 'CasperException' with message 'Connection timed out after 10000 milliseconds' in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php:165 Stack trace: #0 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php(73): CasperAgent->request('/snapchat/attes...', Array) #1 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAPI.php(73): CasperAgent->get('/snapchat/attes...') #2 C:\inetpub\wwwroot\src\snapchat.php(151): CasperAPI->getSnapchatAttestation('QowREDrntgy6DH0...') #3 C:\inetpub\wwwroot\src\snapchat.php(362): Snapchat->getAttestation('xx', 'xx', 1445201697145) #4 C:\inetpub\wwwroot\script\all\xx.php(203): Snapchat->login('xx') #5 {main} thrown in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php on line 165
[/quote]

**Comment by liamcottle** [comment] 2015-10-18 20:59
@mgp25 removing the timeouts will not fix this issue, but will cause others instead. Those timeouts are in there for a reason. ;)

I do believe the current timeout issue, is caused by the SSL on the server.

Sometimes SSL takes forever to load, whereas http loads instantly.

If anyone knows a fix for this, that'll be great.

**Comment by waveur35** [comment] 2015-10-18 21:04
So everyone have actually this problem ? Thanks for your reply liam. :)

**Comment by kkai4u** [comment] 2015-10-18 21:27
Yes I do too @waveur35

**Comment by LanchaBasualdo** [comment] 2015-10-19 01:49
@waveur35 As @liamcottle said. I had the same error, I changed the timeouts to infinite and now I have other problems.

**Comment by liamcottle** [comment] 2015-10-19 04:42
The SSL issue on the server has been fixed. So you shouldn't get this problem anymore.

Unless the server itself is down for another reason.

@mgp25 can you revert https://github.com/mgp25/SC-API/commit/41424592eb22b605e2fc420207ed58b3af30e5a7

The timeouts need to be in there, because Google will provide an invalid attestation if the requests aren't completed within the 10 second timeframe.

Cheers.

**Closed** 2015-10-19 04:42 UTC
Labels: help wanted

**Comment by LanchaBasualdo** [comment] 2015-10-19 10:18
Uncaught exception 'CasperException' with message 'Operation timed out after 20000 milliseconds with 0 bytes received' after downloading latest update.

**Comment by LanchaBasualdo** [comment] 2015-10-19 10:19
Uncaught exception 'CasperException' with message 'Operation timed out after 20000 milliseconds with 0 bytes received' after downloading latest update.

**Comment by liamcottle** [comment] 2015-10-19 10:23
This must be an issue on your end with your internet connection.

I've just checked the server monitors in place, and everything is responding in `800ms`.

No spikes in CPU or Memory, and just tested my local copy of the SC-API, which is working fine.

So I can't really help you here, sorry.

**Comment by LanchaBasualdo** [comment] 2015-10-19 11:03
@mgp25 Thing is that when I run a code with my personal(small) account it works fine. When I run the same code with a larger accout with 2000 friends this error comes up. I dont know what to do.

**Comment by LanchaBasualdo** [comment] 2015-10-19 13:13
debug of Large account: https://www.dropbox.com/s/u0wetjtmec11o3n/Debug%20of%20Large%20account.rtf?dl=0

debig of Small account : 
https://www.dropbox.com/s/lxapymex8fwjvsi/Debug%20of%20Small%20account.rtf?dl=0

**Comment by waveur35** [comment] 2015-10-19 21:23
The issus is still here

**Comment by liamcottle** [comment] 2015-10-19 23:20
@LanchaBasualdo

The issue you have with your 'Large Account', is completely different to this specific issue.

```
PHP Warning: First parameter must either be an object or the name of an existing 
class in /Users/Pilo/Desktop/SC-API-master/src/snapchat_agent.php on line 442

PHP Stack trace:
1. {main}() /Users/Pilo/Desktop/SC-API-master/examples/exampleFunctional.php:0
2. Snapchat->login() /Users/Pilo/Desktop/SC-API-master/examples/exampleFunctional.php:22
3. SnapchatAgent->post() /Users/Pilo/Desktop/SC-API-master/src/snapchat.php:392
4. property_exists() /Users/Pilo/Desktop/SC-API-master/src/snapchat_agent.php:442 Warning: First parameter must either be an object or the name of an existing class in /Users/Pilo/Desktop/SC-API-master/src/snapchat_agent.php on line 442

Call Stack: 
1. {main}() /Users/Pilo/Desktop/SC-API-master/examples/exampleFunctional.php:0
2. Snapchat->login() /Users/Pilo/Desktop/SC-API-master/examples/exampleFunctional.php:22
3. SnapchatAgent->post() /Users/Pilo/Desktop/SC-API-master/src/snapchat.php:392
4. property_exists() /Users/Pilo/Desktop/SC-API-master/src/snapchat_agent.php:442
```

You'll need to go to those lines, and log what the outputs are.

**Comment by LanchaBasualdo** [comment] 2015-10-20 02:08
@liamcottle dude I'm fully aware of that, I'm showing this debugs so as to provide some evidence of problems try to help you guys solve it.
